Document: xf86-video-mali
Title: Debian xf86-video-mali Manual
Author: <insert document author here>
Abstract: This manual describes what xf86-video-mali is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xf86-video-mali/xf86-video-mali.sgml.gz

Format: postscript
Files: /usr/share/doc/xf86-video-mali/xf86-video-mali.ps.gz

Format: text
Files: /usr/share/doc/xf86-video-mali/xf86-video-mali.text.gz

Format: HTML
Index: /usr/share/doc/xf86-video-mali/html/index.html
Files: /usr/share/doc/xf86-video-mali/html/*.html
